# Changes here will be overwritten by Copier
_commit: 8c06bd5
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: rust
email: 3105306+timkpaine@users.noreply.github.com
github: 1kbgz
project_description: Data generation
project_name: superstore
python_version_primary: '3.9'
team: the superstore authors
